"""Localized copy for AI assistant responses."""

from __future__ import annotations

from copy import deepcopy


MESSAGES = {
    "en": {
        "level_labels": {
            "emergency": "Emergency care now",
            "urgent": "Same-day medical visit",
            "soon": "Doctor visit soon",
            "self_care": "Home care with monitoring",
        },
        "headlines": {
            "respiratory_distress": "Possible breathing or heart-related danger sign",
            "possible_infection": "Possible infection that should be checked",
            "possible_dehydration": "Possible dehydration risk",
            "pregnancy_warning": "Pregnancy warning sign needs review",
            "injury_or_pain": "Injury or pain may need clinical assessment",
            "routine_review": "Needs a routine PHC review",
            "mild_self_care": "Looks suitable for self-care if symptoms stay mild",
            "metabolic_followup": "Blood sugar issue may need follow-up",
        },
        "level_explanations": {
            "emergency": "This pattern includes warning signs that should not wait for a routine appointment.",
            "urgent": "A clinician should assess this today, especially if symptoms are getting worse.",
            "soon": "This is not an immediate emergency from the information given, but it should still be checked soon.",
            "self_care": "The symptoms sound mild right now, but keep monitoring closely.",
        },
        "action_texts": {
            "call_108_or_112": "Call 108 or 112 if transport or emergency support is needed.",
            "go_now": "Go to the nearest district hospital or emergency facility now.",
            "do_not_delay": "Do not delay care because of home remedies alone.",
            "carry_records": "Carry current medicines, old prescriptions, and ID if available.",
            "visit_today": "Visit a PHC or CHC today.",
            "fluids_if_alert": "Sip safe water or ORS if the person is awake and able to drink.",
            "avoid_self_medicating": "Avoid starting antibiotics or steroids without a clinician's advice.",
            "book_within_24h": "Try to get a PHC appointment within 24 hours.",
            "note_vitals": "Note fever duration, blood sugar, BP, or other readings if you have them.",
            "rest_and_fluids": "Rest, drink safe fluids, and eat simple food if tolerated.",
            "monitor_24h": "Monitor symptoms over the next 24 hours.",
            "ask_asha_for_help": "Ask an ASHA worker or local health worker to help with follow-up if needed.",
        },
        "care_texts": {
            "hydration": "Drink safe fluids in small repeated sips.",
            "ors": "Use ORS for loose motions or vomiting unless a clinician has told you otherwise.",
            "rest": "Take rest and avoid heavy travel if possible.",
            "food_light": "Choose light food like khichdi, rice, curd, or soup if tolerated.",
            "isolate_mask": "If cough or fever is present, use masking and avoid close contact with vulnerable family members.",
            "medicine_check": "Continue only medicines already prescribed unless a clinician changes them.",
        },
        "red_flag_texts": {
            "worse_breathing": "breathing gets worse",
            "persistent_fever": "fever continues or rises",
            "blood_loss": "bleeding starts or increases",
            "confusion": "the person becomes confused, faints, or is difficult to wake",
            "can_not_drink": "the person cannot drink or keep fluids down",
            "one_sided_weakness": "one-sided weakness, face droop, or speech trouble appears",
            "severe_pain": "severe chest pain or severe abdominal pain starts",
            "pregnancy_movement": "reduced fetal movement or pregnancy bleeding happens",
        },
        "specialty_labels": {
            "general_medicine": "General medicine",
            "maternal_health": "Maternal health",
            "pediatrics": "Pediatrics",
            "emergency": "Emergency",
        },
        "facility_labels": {
            "phc": "Primary Health Centre",
            "chc": "Community Health Centre",
            "district_hospital": "District hospital",
        },
        "disclaimer": "This assistant is a first-step guide, not a confirmed diagnosis.",
        "prescription": {
            "meal_relations": {
                "before_food": "before food",
                "after_food": "after food",
                "bedtime": "at bedtime",
                "with_food": "with food",
            },
            "abbr_meanings": {
                "OD": "once daily",
                "BD": "twice daily",
                "BID": "twice daily",
                "TDS": "three times daily",
                "TID": "three times daily",
                "QID": "four times daily",
                "HS": "at bedtime",
                "SOS": "only when needed",
                "AC": "before food",
                "PC": "after food",
                "STAT": "take immediately",
            },
            "warnings": {
                "not_diagnosis": "Do not change the medicine or dose without speaking to a clinician or pharmacist.",
                "unclear": "If handwriting or dose details are unclear, verify with the hospital, doctor, or pharmacist.",
            },
            "time_of_day": {
                "morning": "morning",
                "afternoon": "afternoon",
                "night": "night",
            },
        },
    },
    "hi": {
        "level_labels": {
            "emergency": "तुरंत आपातकालीन देखभाल",
            "urgent": "आज ही डॉक्टर को दिखाएं",
            "soon": "जल्द डॉक्टर से मिलें",
            "self_care": "घर पर देखभाल और निगरानी",
        },
        "headlines": {
            "respiratory_distress": "सांस या दिल से जुड़ा खतरे का संकेत हो सकता है",
            "possible_infection": "संक्रमण की संभावना है, जांच जरूरी है",
            "possible_dehydration": "पानी की कमी का जोखिम हो सकता है",
            "pregnancy_warning": "गर्भावस्था का चेतावनी संकेत है",
            "injury_or_pain": "चोट या दर्द की जांच जरूरी हो सकती है",
            "routine_review": "पीएचसी पर सामान्य जांच करवाएं",
            "mild_self_care": "अभी लक्षण हल्के लग रहे हैं, निगरानी रखें",
            "metabolic_followup": "शुगर की समस्या की जांच करनी चाहिए",
        },
        "level_explanations": {
            "emergency": "दिए गए लक्षण ऐसे हैं जिन्हें सामान्य अपॉइंटमेंट तक टालना ठीक नहीं है।",
            "urgent": "आज ही किसी स्वास्थ्यकर्मी से जांच करवानी चाहिए, खासकर यदि हालत बिगड़ रही हो।",
            "soon": "दी गई जानकारी के आधार पर यह तुरंत आपातकाल नहीं लगता, लेकिन जल्द जांच जरूरी है।",
            "self_care": "अभी लक्षण हल्के लग रहे हैं, फिर भी ध्यान से निगरानी रखें।",
        },
        "action_texts": {
            "call_108_or_112": "जरूरत हो तो 108 या 112 पर कॉल करें।",
            "go_now": "अभी नजदीकी जिला अस्पताल या आपातकालीन केंद्र जाएं।",
            "do_not_delay": "केवल घरेलू उपायों पर भरोसा करके इलाज में देर न करें।",
            "carry_records": "मौजूदा दवाइयां, पुराने पर्चे और पहचान पत्र साथ रखें।",
            "visit_today": "आज ही पीएचसी या सीएचसी जाएं।",
            "fluids_if_alert": "यदि व्यक्ति होश में है और पी सकता है तो साफ पानी या ओआरएस थोड़ी-थोड़ी मात्रा में दें।",
            "avoid_self_medicating": "डॉक्टर की सलाह बिना एंटीबायोटिक या स्टेरॉयड शुरू न करें।",
            "book_within_24h": "24 घंटे के भीतर पीएचसी अपॉइंटमेंट लेने की कोशिश करें।",
            "note_vitals": "बुखार कितने दिन से है, शुगर, बीपी या अन्य रीडिंग लिख लें।",
            "rest_and_fluids": "आराम करें, सुरक्षित तरल पिएं और हल्का भोजन लें।",
            "monitor_24h": "अगले 24 घंटे तक लक्षणों पर नजर रखें।",
            "ask_asha_for_help": "जरूरत हो तो ASHA कार्यकर्ता या स्थानीय स्वास्थ्यकर्मी से मदद लें।",
        },
        "care_texts": {
            "hydration": "सुरक्षित तरल थोड़ी-थोड़ी मात्रा में बार-बार लें।",
            "ors": "दस्त या उल्टी में ओआरएस उपयोग करें, जब तक डॉक्टर ने मना न किया हो।",
            "rest": "आराम करें और संभव हो तो लंबी यात्रा से बचें।",
            "food_light": "खिचड़ी, चावल, दही या सूप जैसा हल्का खाना लें।",
            "isolate_mask": "खांसी या बुखार हो तो मास्क पहनें और कमजोर परिवारजनों से दूरी रखें।",
            "medicine_check": "पहले से लिखी दवाइयां ही जारी रखें जब तक डॉक्टर बदलाव न करें।",
        },
        "red_flag_texts": {
            "worse_breathing": "सांस लेने में दिक्कत बढ़े",
            "persistent_fever": "बुखार बना रहे या बढ़ जाए",
            "blood_loss": "खून आना शुरू हो या बढ़ जाए",
            "confusion": "व्यक्ति बेहोश, भ्रमित या जगाने में कठिन हो",
            "can_not_drink": "व्यक्ति पानी न पी सके या सब उल्टी हो जाए",
            "one_sided_weakness": "चेहरा टेढ़ा हो, एक तरफ कमजोरी आए या बोलने में दिक्कत हो",
            "severe_pain": "तेज सीने या पेट का दर्द शुरू हो",
            "pregnancy_movement": "बच्चे की हरकत कम हो जाए या गर्भावस्था में खून आए",
        },
        "specialty_labels": {
            "general_medicine": "जनरल मेडिसिन",
            "maternal_health": "मातृ स्वास्थ्य",
            "pediatrics": "बाल रोग",
            "emergency": "आपातकाल",
        },
        "facility_labels": {
            "phc": "प्राथमिक स्वास्थ्य केंद्र",
            "chc": "सामुदायिक स्वास्थ्य केंद्र",
            "district_hospital": "जिला अस्पताल",
        },
        "disclaimer": "यह सहायक केवल शुरुआती मार्गदर्शन देता है, पक्की बीमारी नहीं बताता।",
        "prescription": {
            "meal_relations": {
                "before_food": "खाने से पहले",
                "after_food": "खाने के बाद",
                "bedtime": "सोते समय",
                "with_food": "खाने के साथ",
            },
            "abbr_meanings": {
                "OD": "दिन में 1 बार",
                "BD": "दिन में 2 बार",
                "BID": "दिन में 2 बार",
                "TDS": "दिन में 3 बार",
                "TID": "दिन में 3 बार",
                "QID": "दिन में 4 बार",
                "HS": "सोते समय",
                "SOS": "जरूरत होने पर",
                "AC": "खाने से पहले",
                "PC": "खाने के बाद",
                "STAT": "तुरंत लें",
            },
            "warnings": {
                "not_diagnosis": "डॉक्टर या फार्मासिस्ट से पूछे बिना दवा या डोज न बदलें।",
                "unclear": "अगर लिखावट या डोज साफ न हो तो अस्पताल, डॉक्टर या फार्मासिस्ट से पुष्टि करें।",
            },
            "time_of_day": {
                "morning": "सुबह",
                "afternoon": "दोपहर",
                "night": "रात",
            },
        },
    },
    "bn": {
        "level_labels": {
            "emergency": "এখনই জরুরি চিকিৎসা",
            "urgent": "আজই ডাক্তার দেখান",
            "soon": "শীঘ্রই ডাক্তার দেখান",
            "self_care": "বাড়িতে যত্ন ও নজরদারি",
        },
        "headlines": {
            "respiratory_distress": "শ্বাস বা হৃদ্‌যন্ত্রজনিত বিপদের লক্ষণ হতে পারে",
            "possible_infection": "সংক্রমণ হতে পারে, পরীক্ষা দরকার",
            "possible_dehydration": "পানিশূন্যতার ঝুঁকি থাকতে পারে",
            "pregnancy_warning": "গর্ভাবস্থার সতর্কবার্তা",
            "injury_or_pain": "চোট বা ব্যথা পরীক্ষা করা দরকার হতে পারে",
            "routine_review": "পিএইচসি-তে রুটিন পরীক্ষা দরকার",
            "mild_self_care": "এখন লক্ষণ হালকা মনে হচ্ছে, তবু নজর রাখুন",
            "metabolic_followup": "সুগার সমস্যার ফলো-আপ দরকার হতে পারে",
        },
        "level_explanations": {
            "emergency": "এই লক্ষণগুলো নিয়মিত অ্যাপয়েন্টমেন্ট পর্যন্ত অপেক্ষা করা ঠিক নয়।",
            "urgent": "আজই স্বাস্থ্যকর্মীকে দেখানো উচিত, বিশেষ করে যদি অবস্থা খারাপ হয়।",
            "soon": "এখনই জরুরি অবস্থা না-ও হতে পারে, কিন্তু দ্রুত পরীক্ষা দরকার।",
            "self_care": "এই মুহূর্তে লক্ষণ হালকা, তবে ভালো করে নজর রাখুন।",
        },
        "action_texts": {
            "call_108_or_112": "প্রয়োজনে 108 বা 112-এ ফোন করুন।",
            "go_now": "এখনই নিকটবর্তী জেলা হাসপাতাল বা জরুরি কেন্দ্রে যান।",
            "do_not_delay": "শুধু ঘরোয়া উপায়ে চিকিৎসা দেরি করবেন না।",
            "carry_records": "ওষুধ, পুরনো প্রেসক্রিপশন ও পরিচয়পত্র সঙ্গে নিন।",
            "visit_today": "আজই পিএইচসি বা সিএইচসি-তে যান।",
            "fluids_if_alert": "রোগী সচেতন থাকলে ওরস বা নিরাপদ পানি অল্প অল্প করে দিন।",
            "avoid_self_medicating": "ডাক্তারের পরামর্শ ছাড়া অ্যান্টিবায়োটিক বা স্টেরয়েড শুরু করবেন না।",
            "book_within_24h": "২৪ ঘণ্টার মধ্যে পিএইচসি অ্যাপয়েন্টমেন্ট নেওয়ার চেষ্টা করুন।",
            "note_vitals": "জ্বরের দিন, সুগার, BP বা অন্য রিডিং লিখে রাখুন।",
            "rest_and_fluids": "বিশ্রাম নিন, নিরাপদ তরল পান করুন, হালকা খাবার খান।",
            "monitor_24h": "পরের ২৪ ঘণ্টা লক্ষণ দেখুন।",
            "ask_asha_for_help": "প্রয়োজনে ASHA কর্মী বা স্থানীয় স্বাস্থ্যকর্মীর সাহায্য নিন।",
        },
        "care_texts": {
            "hydration": "অল্প অল্প করে বারবার নিরাপদ তরল পান করুন।",
            "ors": "ডায়রিয়া বা বমিতে ORS ব্যবহার করুন, যদি চিকিৎসক নিষেধ না করেন।",
            "rest": "বিশ্রাম নিন এবং অপ্রয়োজনীয় ভ্রমণ এড়িয়ে চলুন।",
            "food_light": "খিচুড়ি, ভাত, দই বা স্যুপের মতো হালকা খাবার খান।",
            "isolate_mask": "কাশি বা জ্বর থাকলে মাস্ক ব্যবহার করুন এবং ঝুঁকিপূর্ণ সদস্যদের থেকে দূরে থাকুন।",
            "medicine_check": "চিকিৎসক না বদলালে আগের ওষুধই চালিয়ে যান।",
        },
        "red_flag_texts": {
            "worse_breathing": "শ্বাসকষ্ট বাড়ে",
            "persistent_fever": "জ্বর থাকে বা বাড়ে",
            "blood_loss": "রক্তপাত শুরু হয় বা বাড়ে",
            "confusion": "রোগী বিভ্রান্ত, অজ্ঞান বা জাগানো কঠিন হয়",
            "can_not_drink": "রোগী পানি খেতে পারে না বা সব বমি হয়ে যায়",
            "one_sided_weakness": "এক পাশ দুর্বল হয়, মুখ বেঁকে যায় বা কথা জড়িয়ে যায়",
            "severe_pain": "বুকে বা পেটে তীব্র ব্যথা শুরু হয়",
            "pregnancy_movement": "শিশুর নড়াচড়া কমে যায় বা গর্ভাবস্থায় রক্তপাত হয়",
        },
        "specialty_labels": {
            "general_medicine": "জেনারেল মেডিসিন",
            "maternal_health": "মাতৃস্বাস্থ্য",
            "pediatrics": "শিশুরোগ",
            "emergency": "জরুরি",
        },
        "facility_labels": {
            "phc": "প্রাথমিক স্বাস্থ্যকেন্দ্র",
            "chc": "কমিউনিটি হেলথ সেন্টার",
            "district_hospital": "জেলা হাসপাতাল",
        },
        "disclaimer": "এই সহায়কটি প্রাথমিক দিকনির্দেশনা দেয়, নিশ্চিত রোগ নির্ণয় নয়।",
        "prescription": {
            "meal_relations": {
                "before_food": "খাওয়ার আগে",
                "after_food": "খাওয়ার পরে",
                "bedtime": "ঘুমানোর সময়",
                "with_food": "খাবারের সাথে",
            },
            "abbr_meanings": {
                "OD": "দিনে ১ বার",
                "BD": "দিনে ২ বার",
                "BID": "দিনে ২ বার",
                "TDS": "দিনে ৩ বার",
                "TID": "দিনে ৩ বার",
                "QID": "দিনে ৪ বার",
                "HS": "ঘুমানোর আগে",
                "SOS": "প্রয়োজনে",
                "AC": "খাবারের আগে",
                "PC": "খাবারের পরে",
                "STAT": "সঙ্গে সঙ্গে নিন",
            },
            "warnings": {
                "not_diagnosis": "চিকিৎসক বা ফার্মাসিস্টের সঙ্গে কথা না বলে ওষুধ বা ডোজ বদলাবেন না।",
                "unclear": "লেখা বা ডোজ স্পষ্ট না হলে হাসপাতাল, ডাক্তার বা ফার্মাসিস্টের সঙ্গে মিলিয়ে নিন।",
            },
            "time_of_day": {
                "morning": "সকাল",
                "afternoon": "দুপুর",
                "night": "রাত",
            },
        },
    },
    "mr": {
        "level_labels": {
            "emergency": "तात्काळ आपत्कालीन उपचार",
            "urgent": "आजच डॉक्टरांना दाखवा",
            "soon": "लवकर डॉक्टरांना दाखवा",
            "self_care": "घरी काळजी आणि निरीक्षण",
        },
        "headlines": {
            "respiratory_distress": "श्वास किंवा हृदयाशी संबंधित धोक्याचे लक्षण असू शकते",
            "possible_infection": "संसर्ग असू शकतो, तपासणी हवी",
            "possible_dehydration": "पाण्याची कमतरता असण्याची शक्यता",
            "pregnancy_warning": "गर्भावस्थेतील इशारा",
            "injury_or_pain": "इजा किंवा वेदनेची तपासणी आवश्यक असू शकते",
            "routine_review": "PHC मध्ये नियमित तपासणी करा",
            "mild_self_care": "आत्तासाठी लक्षणे सौम्य वाटत आहेत, निरीक्षण ठेवा",
            "metabolic_followup": "साखरेच्या समस्येची पुढील तपासणी हवी",
        },
        "level_explanations": {
            "emergency": "ही चिन्हे सामान्य भेटीपर्यंत थांबवू नयेत.",
            "urgent": "आजच आरोग्यकर्म्यांना दाखवणे योग्य आहे, विशेषतः त्रास वाढत असेल तर.",
            "soon": "ही तातडीची आपत्कालीन स्थिती नसली तरी लवकर तपासणी हवी.",
            "self_care": "लक्षणे हलकी वाटत असली तरी काळजीपूर्वक निरीक्षण ठेवा.",
        },
        "action_texts": {
            "call_108_or_112": "गरज असल्यास 108 किंवा 112 वर कॉल करा.",
            "go_now": "आत्ताच जवळच्या जिल्हा रुग्णालयात किंवा आपत्कालीन केंद्रात जा.",
            "do_not_delay": "फक्त घरगुती उपायांमुळे उपचार उशीर करू नका.",
            "carry_records": "सध्याची औषधे, जुने प्रिस्क्रिप्शन आणि ओळखपत्र सोबत घ्या.",
            "visit_today": "आजच PHC किंवा CHC ला भेट द्या.",
            "fluids_if_alert": "व्यक्ती शुद्धीत असेल आणि पिऊ शकत असेल तर सुरक्षित पाणी किंवा ORS द्या.",
            "avoid_self_medicating": "डॉक्टरांशिवाय अँटिबायोटिक किंवा स्टेरॉइड सुरू करू नका.",
            "book_within_24h": "24 तासांत PHC भेट ठरवण्याचा प्रयत्न करा.",
            "note_vitals": "ताप किती दिवस आहे, साखर, BP किंवा इतर मोजमाप लिहून ठेवा.",
            "rest_and_fluids": "विश्रांती घ्या, सुरक्षित द्रव प्या आणि हलके अन्न घ्या.",
            "monitor_24h": "पुढील 24 तास लक्षणांवर लक्ष ठेवा.",
            "ask_asha_for_help": "गरज असल्यास ASHA किंवा स्थानिक आरोग्यकर्म्यांची मदत घ्या.",
        },
        "care_texts": {
            "hydration": "थोडेथोडे करून वारंवार सुरक्षित द्रव घ्या.",
            "ors": "जुलाब किंवा उलटी असल्यास डॉक्टरांनी मनाई केली नसेल तर ORS घ्या.",
            "rest": "विश्रांती घ्या आणि शक्य असल्यास प्रवास टाळा.",
            "food_light": "खिचडी, भात, दही किंवा सूपसारखे हलके अन्न घ्या.",
            "isolate_mask": "खोकला किंवा ताप असल्यास मास्क वापरा आणि संवेदनशील सदस्यांपासून अंतर ठेवा.",
            "medicine_check": "डॉक्टरांनी बदल सांगितला नसेल तर आधीची औषधेच चालू ठेवा.",
        },
        "red_flag_texts": {
            "worse_breathing": "श्वास घेण्यास अधिक त्रास होतो",
            "persistent_fever": "ताप टिकून राहतो किंवा वाढतो",
            "blood_loss": "रक्तस्राव सुरू होतो किंवा वाढतो",
            "confusion": "व्यक्ती गोंधळलेली, बेशुद्ध किंवा उठवणे कठीण होते",
            "can_not_drink": "व्यक्ती पाणी पिऊ शकत नाही किंवा सारखी उलटी होते",
            "one_sided_weakness": "एका बाजूला अशक्तपणा, चेहरा वाकडा किंवा बोलण्यात अडचण येते",
            "severe_pain": "छातीत किंवा पोटात तीव्र वेदना सुरू होतात",
            "pregnancy_movement": "बाळाची हालचाल कमी होते किंवा गर्भावस्थेत रक्तस्राव होतो",
        },
        "specialty_labels": {
            "general_medicine": "सामान्य औषधोपचार",
            "maternal_health": "मातृ आरोग्य",
            "pediatrics": "बालरोग",
            "emergency": "आपत्काल",
        },
        "facility_labels": {
            "phc": "प्राथमिक आरोग्य केंद्र",
            "chc": "समुदाय आरोग्य केंद्र",
            "district_hospital": "जिल्हा रुग्णालय",
        },
        "disclaimer": "हा सहाय्यक फक्त प्राथमिक मार्गदर्शन देतो, निश्चित निदान नाही.",
        "prescription": {
            "meal_relations": {
                "before_food": "जेवणाआधी",
                "after_food": "जेवणानंतर",
                "bedtime": "झोपताना",
                "with_food": "जेवणासोबत",
            },
            "abbr_meanings": {
                "OD": "दिवसातून 1 वेळ",
                "BD": "दिवसातून 2 वेळा",
                "BID": "दिवसातून 2 वेळा",
                "TDS": "दिवसातून 3 वेळा",
                "TID": "दिवसातून 3 वेळा",
                "QID": "दिवसातून 4 वेळा",
                "HS": "झोपताना",
                "SOS": "गरज असल्यास",
                "AC": "जेवणाआधी",
                "PC": "जेवणानंतर",
                "STAT": "ताबडतोब घ्या",
            },
            "warnings": {
                "not_diagnosis": "डॉक्टर किंवा फार्मासिस्टचा सल्ला न घेता औषध किंवा डोस बदलू नका.",
                "unclear": "लिहिणे किंवा डोस स्पष्ट नसेल तर रुग्णालय, डॉक्टर किंवा फार्मासिस्टकडून खात्री करा.",
            },
            "time_of_day": {
                "morning": "सकाळ",
                "afternoon": "दुपार",
                "night": "रात्र",
            },
        },
    },
    "ta": {
        "level_labels": {
            "emergency": "உடனடி அவசர சிகிச்சை",
            "urgent": "இன்றே மருத்துவரை பார்க்கவும்",
            "soon": "விரைவில் மருத்துவரை பார்க்கவும்",
            "self_care": "வீட்டிலேயே கவனம் மற்றும் கண்காணிப்பு",
        },
        "headlines": {
            "respiratory_distress": "மூச்சு அல்லது இதயம் தொடர்பான ஆபத்து அறிகுறி இருக்கலாம்",
            "possible_infection": "தொற்று இருக்கலாம், பரிசோதனை தேவை",
            "possible_dehydration": "நீரிழப்பு அபாயம் இருக்கலாம்",
            "pregnancy_warning": "கர்ப்பகால எச்சரிக்கை அறிகுறி",
            "injury_or_pain": "காயம் அல்லது வலி பரிசோதனை தேவைப்படலாம்",
            "routine_review": "PHC-யில் வழக்கமான பரிசோதனை செய்யவும்",
            "mild_self_care": "இப்போது அறிகுறிகள் லேசாக தோன்றுகின்றன, கவனமாக பார்த்துக்கொள்ளவும்",
            "metabolic_followup": "சர்க்கரை பிரச்சனைக்கு பின்தொடர் பரிசோதனை தேவைப்படலாம்",
        },
        "level_explanations": {
            "emergency": "இந்த அறிகுறிகள் சாதாரண நேர்முகப் பார்வை வரைக்கும் காத்திருக்கக் கூடாது.",
            "urgent": "இன்றே சுகாதார நிபுணர் பார்க்க வேண்டும், குறிப்பாக நிலை மோசமாகினால்.",
            "soon": "இது உடனடி அவசரம் அல்லாமல் இருக்கலாம், ஆனால் விரைவில் பார்க்க வேண்டும்.",
            "self_care": "அறிகுறிகள் இப்போது லேசாக இருந்தாலும் கவனமாக கண்காணிக்கவும்.",
        },
        "action_texts": {
            "call_108_or_112": "தேவையெனில் 108 அல்லது 112-க்கு அழைக்கவும்.",
            "go_now": "இப்போது அருகிலுள்ள மாவட்ட மருத்துவமனை அல்லது அவசர மையத்துக்கு செல்லவும்.",
            "do_not_delay": "வீட்டு வைத்தியத்தால் மட்டும் சிகிச்சையை தாமதிக்க வேண்டாம்.",
            "carry_records": "இப்போது எடுத்துக்கொண்டு இருக்கும் மருந்துகள், பழைய சீட்டுகள், அடையாள அட்டை ஆகியவற்றை எடுத்துச் செல்லவும்.",
            "visit_today": "இன்றே PHC அல்லது CHC-க்கு செல்லவும்.",
            "fluids_if_alert": "நபர் விழிப்புடன் இருந்து குடிக்க முடிந்தால், பாதுகாப்பான தண்ணீர் அல்லது ORS கொடுக்கவும்.",
            "avoid_self_medicating": "மருத்துவர் ஆலோசனை இல்லாமல் ஆன்டிபயாட்டிக் அல்லது ஸ்டீராய்டு தொடங்க வேண்டாம்.",
            "book_within_24h": "24 மணி நேரத்திற்குள் PHC நேரம் பெற முயலுங்கள்.",
            "note_vitals": "காய்ச்சல் எத்தனை நாளாக உள்ளது, சர்க்கரை, BP போன்ற விவரங்களை குறித்துக் கொள்ளவும்.",
            "rest_and_fluids": "ஓய்வு எடுத்துக் கொள்ளவும், பாதுகாப்பான திரவங்களை குடிக்கவும், லேசான உணவு சாப்பிடவும்.",
            "monitor_24h": "அடுத்த 24 மணி நேரம் அறிகுறிகளை கவனிக்கவும்.",
            "ask_asha_for_help": "தேவைப்பட்டால் ASHA பணியாளர் அல்லது உள்ளூர் சுகாதார பணியாளரிடம் உதவி கேளுங்கள்.",
        },
        "care_texts": {
            "hydration": "சிறுசிறு அளவில் பாதுகாப்பான திரவங்களை அடிக்கடி குடிக்கவும்.",
            "ors": "வயிற்றுப்போக்கு அல்லது வாந்தி இருந்தால் மருத்துவர் தடையில்லை என்றால் ORS பயன்படுத்தவும்.",
            "rest": "ஓய்வு எடுத்துக் கொண்டு தேவையற்ற பயணத்தை தவிர்க்கவும்.",
            "food_light": "கஞ்சி, சாதம், தயிர் அல்லது சூப் போன்ற லேசான உணவு எடுத்துக் கொள்ளவும்.",
            "isolate_mask": "இருமல் அல்லது காய்ச்சல் இருந்தால் முகக்கவசம் அணியவும், பாதிக்கப்படக்கூடிய குடும்பத்தினரிடம் இருந்து தூரம் வைக்கவும்.",
            "medicine_check": "மருத்துவர் மாற்றம் சொல்லாவிட்டால் ஏற்கெனவே கொடுத்த மருந்துகளை மட்டும் தொடரவும்.",
        },
        "red_flag_texts": {
            "worse_breathing": "மூச்சுத்திணறல் அதிகரிக்கிறது",
            "persistent_fever": "காய்ச்சல் தொடர்கிறது அல்லது அதிகரிக்கிறது",
            "blood_loss": "ரத்தப்போக்கு தொடங்குகிறது அல்லது அதிகரிக்கிறது",
            "confusion": "நபர் குழப்பமாகிறார், மயக்கம் அல்லது எழுப்ப முடியாத நிலை வருகிறது",
            "can_not_drink": "நபர் குடிக்க முடியவில்லை அல்லது குடித்ததும் வாந்தி வருகிறது",
            "one_sided_weakness": "ஒருபக்க பலவீனம், முகம் சாய்வு அல்லது பேச்சு சிரமம் தோன்றுகிறது",
            "severe_pain": "கடுமையான மார்பு வலி அல்லது வயிற்று வலி தொடங்குகிறது",
            "pregnancy_movement": "கர்ப்பத்தில் குழந்தை அசைவு குறைகிறது அல்லது ரத்தப்போக்கு வருகிறது",
        },
        "specialty_labels": {
            "general_medicine": "பொது மருத்துவம்",
            "maternal_health": "தாய் நலம்",
            "pediatrics": "குழந்தைகள் மருத்துவம்",
            "emergency": "அவசரம்",
        },
        "facility_labels": {
            "phc": "முதன்மை சுகாதார மையம்",
            "chc": "சமூக சுகாதார மையம்",
            "district_hospital": "மாவட்ட மருத்துவமனை",
        },
        "disclaimer": "இந்த உதவியாளர் ஆரம்ப வழிகாட்டுதலுக்கே, உறுதியான நோயறிதல் அல்ல.",
        "prescription": {
            "meal_relations": {
                "before_food": "உணவுக்கு முன்",
                "after_food": "உணவுக்கு பின்",
                "bedtime": "தூங்கும் முன்",
                "with_food": "உணவுடன்",
            },
            "abbr_meanings": {
                "OD": "ஒரு நாளில் 1 முறை",
                "BD": "ஒரு நாளில் 2 முறை",
                "BID": "ஒரு நாளில் 2 முறை",
                "TDS": "ஒரு நாளில் 3 முறை",
                "TID": "ஒரு நாளில் 3 முறை",
                "QID": "ஒரு நாளில் 4 முறை",
                "HS": "தூங்கும் முன்",
                "SOS": "தேவைப்பட்டால் மட்டும்",
                "AC": "உணவுக்கு முன்",
                "PC": "உணவுக்கு பின்",
                "STAT": "உடனே எடுத்துக் கொள்ளவும்",
            },
            "warnings": {
                "not_diagnosis": "மருத்துவர் அல்லது மருந்தாளர் பேசாமல் மருந்து அல்லது அளவை மாற்ற வேண்டாம்.",
                "unclear": "எழுத்து அல்லது அளவு தெளிவாக இல்லையெனில் மருத்துவமனை, மருத்துவர் அல்லது மருந்தாளரிடம் உறுதிப்படுத்தவும்.",
            },
            "time_of_day": {
                "morning": "காலை",
                "afternoon": "மதியம்",
                "night": "இரவு",
            },
        },
    },
}


def _deep_merge(base: dict, override: dict) -> dict:
    merged = deepcopy(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = deepcopy(value)
    return merged


def copy_for(language: str) -> dict:
    base = MESSAGES["en"]
    if language == "en":
        return deepcopy(base)

    override = MESSAGES.get(language)
    if not override:
        return deepcopy(base)

    return _deep_merge(base, override)
